using GeneratorLibrary;
using Microsoft.CodeAnalysis;
using System;
using System.Linq;
using System.Reflection;
using System.Text;

namespace MvvmToolbox.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public partial class ObservableModelGenerator : Generator
{
    private const string ObservableModelObjectAttribute = "MvvmToolbox.ComponentModel.ObservableModelObjectAttribute";
    private const string ObservableModelPropertyAttribute = "MvvmToolbox.ComponentModel.ObservableModelPropertyAttribute";

    //private const string FindFieldsGeneratorAttribute = "MediaDevices.FindFieldsGeneratorAttribute";
    //private const string EnumGuidAttribute = "MediaDevices.EnumGuidAttribute";
    //private const string KeyAttribute = "MediaDevices.KeyAttribute";

    public override void Execute()
    {
        //Location errorLocation = propertySyntax.GetLocation();
        //string propertyName = propertySyntax.Identifier.Text;

        //Diagnostic diagnostic = Diagnostic.Create(GeneratorDiagnostics.InvalidPropertyError, errorLocation, propertyName);  // Befüllt das '{0}' im messageFormat
        //Context.ReportDiagnostic(diagnostic);

        //ReportError("Test");

        //Debugger.Launch();
        CreateDebug();

        // get all classes with [ObservableModelObjectAttribute] 
        foreach (var cl in GetAllClassesWithAttribute(ObservableModelObjectAttribute))
        {
            CreateClassFile(cl);
        }
       
    }

    protected override void CreateAttributes(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource($"ObservableModelAttributes.g.cs",
            """
            #nullable enable

            namespace MvvmToolbox.ComponentModel;

            [AttributeUsage(AttributeTargets.Class)]
            public class ObservableModelObjectAttribute(Type modelType): Attribute
            { 
                public Type ModelType { get; } = modelType;
            }

            [AttributeUsage(AttributeTargets.Property)]
            public class ObservableModelPropertyAttribute : Attribute
            { 
                public ObservableModelPropertyAttribute()
                { }

                public ObservableModelPropertyAttribute(string modelPropertyName)
                {
                    ModelPropertyName = modelPropertyName;
                }

                public string? ModelPropertyName { get; } = null; 
                public string? Converter { get; init; }
                public string? ModelType { get; init; }
            }
            """);
    }

    private void CreateClassFile(Class cl)
    {
        var attr = cl.GetAttribute(ObservableModelObjectAttribute);
        string modelType = attr != null ? attr.ConstructorArguments.FirstOrDefault().Value : string.Empty;
        

        StringBuilder sb = new(
            $$"""
            // <auto-generated />

            #nullable enable annotations
            #nullable disable warnings

            // Suppress warnings about [Obsolete] member usage in generated code.
            #pragma warning disable CS0612, CS0618
            
            namespace {{cl.NameSpace}};

            partial class {{cl.Name}}
            {
                public readonly {{modelType}} Model;
                
                public {{cl.Name}}({{modelType}} model)
                {
                    Model = model;

            """);

        foreach (var prop in cl.Properties)
        {
            var propAttr = prop.GetAttribute(ObservableModelPropertyAttribute);
            if (propAttr != null)
            {
                DataType dataType = GetDataType(cl, prop, propAttr);
                string modelPropertyName = propAttr.ConstructorArguments.FirstOrDefault()?.Value ?? prop.Name;
                string viewModelPropertyType = (prop.Type.IsObservableCollection ? prop.Type.GetInnerType()!.FullName : prop.Type.FullName).TrimEnd('?');
                string? modelPropertyType = propAttr.GetNamedArgument("ModelType")?.Value?.ToString() ?? null;
                string? converterName = propAttr.GetNamedArgument("Converter")?.Value?.ToString() ?? null;

                sb.AppendLine(CreateConstructorLine(dataType, prop.Name, viewModelPropertyType, modelPropertyName, modelPropertyType, converterName));
            }
        }

        sb.AppendLine(
            """
                }

            """);

        foreach (var prop in cl.Properties)
        {
            var propAttr = prop.GetAttribute(ObservableModelPropertyAttribute);
            if (propAttr != null)
            {
                DataType dataType = GetDataType(cl, prop, propAttr);
                string modelPropertyName = propAttr.ConstructorArguments.FirstOrDefault()?.Value ?? prop.Name;
                string viewModelPropertyType = (prop.Type.IsObservableCollection ? prop.Type.GetInnerType()!.FullName : prop.Type.FullName); //.TrimEnd('?');
                string? modelPropertyType = propAttr.GetNamedArgument("ModelType")?.Value?.ToString() ?? null;
                string? converterName = propAttr.GetNamedArgument("Converter")?.Value?.ToString() ?? null;

                sb.AppendLine(CreateSetterMethods(dataType, prop.Name, viewModelPropertyType, modelPropertyName, modelPropertyType, converterName));
            }
        }

        sb.AppendLine(
            """
            }
            """);
        AddSource($"{cl.Name}.g.cs", sb.ToString());
    }

    public enum DataType
    {
        Error,
        Simple,
        Model,
        List,
        ModelList,
        Converter,
    }

    public DataType GetDataType(Class cl, Property prop, GeneratorLibrary.Attribute propAttr)
    {
        if (propAttr.HasNamedArgument("Converter"))
        {
            return DataType.Converter;
        }
        else if (prop.Type.IsObservableCollection)
        {
            var innerType = prop.Type.GetInnerType()!;
            if (innerType.ImplementsInterface("System.ComponentModel.INotifyPropertyChanged"))
            {
                // type is a ViewModel type, because it implements INotifyPropertyChanged
                return DataType.ModelList;
            }
            else
            {
                return DataType.List;
            }
        }
        else
        {
            if (prop.Type.ImplementsInterface("System.ComponentModel.INotifyPropertyChanged"))
            {
                return DataType.Model;
            }
            else
            {
                return DataType.Simple;
            }
        }
    }
    
    public string CreateConstructorLine(DataType dataType, string viewModelPropertyName, string viewModelPropertyType, string modelPropertyName, string? modelPropertyType, string? converterName)
    {
        return $"        // {dataType}: vmName: {viewModelPropertyName} vmType: {viewModelPropertyType} mName: {modelPropertyName} mType: {modelPropertyType} converter: {converterName}\r\n" +
            dataType switch
        {
            DataType.Error => string.Empty,
            DataType.Simple =>      
                $"        {viewModelPropertyName} = model.{modelPropertyName};",
            DataType.Model =>       
                $"        {viewModelPropertyName} = model.{modelPropertyName} != null ? new {viewModelPropertyType}(model.{modelPropertyName}) : new {viewModelPropertyType}(new ());",
            DataType.List =>        
                $$"""
                        {{viewModelPropertyName}} = [.. model.{{modelPropertyName}}];
                        {{viewModelPropertyName}}.CollectionChanged += On{{viewModelPropertyName}}CollectionChanged;
                """,
            DataType.ModelList =>   
                $$"""
                        {{viewModelPropertyName}} = [.. (model.{{modelPropertyName}} ?? []).Select(m => new {{viewModelPropertyType}}(m))];
                        {{viewModelPropertyName}}.CollectionChanged += On{{viewModelPropertyName}}CollectionChanged;
                """,
            DataType.Converter => 
                $"        {viewModelPropertyName} = Get{converterName}(model.{modelPropertyName});",
            _ => throw new ArgumentOutOfRangeException(nameof(dataType), dataType, null)
        };
    }

    public string CreateSetterMethods(DataType dataType, string viewModelPropertyName, string viewModelPropertyType, string modelPropertyName, string? modelPropertyType, string? converterName)
    {
        return $"    // {dataType}: vmName: {viewModelPropertyName} vmType: {viewModelPropertyType} mName: {modelPropertyName} mType: {modelPropertyType} converter: {converterName}\r\n" +
            dataType switch
        {
            DataType.Error => string.Empty,
            DataType.Simple =>
                $$"""
                    partial void On{{viewModelPropertyName}}Changed({{viewModelPropertyType}} value)
                    {
                        Model.{{modelPropertyName}} = value;
                    }

                """,
            DataType.Model =>
                $$"""
                    partial void On{{viewModelPropertyName}}Changed({{viewModelPropertyType}} value)
                    {
                        Model.{{modelPropertyName}} = value.Model;
                    }

                """,
            DataType.List =>
                $$"""
                    private void On{{viewModelPropertyName}}CollectionChanged(object? sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                    {
                        Model.{{modelPropertyName}} ??= [];
                        switch (e.Action)
                        {
                        case System.Collections.Specialized.NotifyCollectionChangedAction.Add when e.NewItems != null:
                            int index = e.NewStartingIndex;
                            foreach ({{viewModelPropertyType}} item in e.NewItems)
                            {
                                Model.{{modelPropertyName}}.Insert(index++, item);
                            }
                            break;
                        case System.Collections.Specialized.NotifyCollectionChangedAction.Remove when e.OldItems != null:
                            foreach ({{viewModelPropertyType}} item in e.OldItems)
                            {
                                 Model.{{modelPropertyName}}.Remove(item);
                            }
                            break;
                        case System.Collections.Specialized.NotifyCollectionChangedAction.Move:
                            var modelToMove =  Model.{{modelPropertyName}}[e.OldStartingIndex];
                            Model.{{modelPropertyName}}.RemoveAt(e.OldStartingIndex);
                            Model.{{modelPropertyName}}.Insert(e.NewStartingIndex, modelToMove);
                            break;
                        case System.Collections.Specialized.NotifyCollectionChangedAction.Replace when e.NewItems != null:
                            int replaceIndex = e.NewStartingIndex;
                            foreach ({{viewModelPropertyType}} item in e.NewItems)
                            {
                                Model.{{modelPropertyName}}[replaceIndex++] = item;
                            }
                            break;
                        case System.Collections.Specialized.NotifyCollectionChangedAction.Reset:
                            Model.{{modelPropertyName}}.Clear();
                            foreach ({{viewModelPropertyType}} item in {{viewModelPropertyName}})
                            {
                                Model.{{modelPropertyName}}.Add(item);
                            }
                            break;
                        }   
                    }
                 """,
            DataType.ModelList =>
                $$"""
                     private void On{{viewModelPropertyName}}CollectionChanged(object? sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                     {
                        Model.{{modelPropertyName}} ??= [];
                         switch (e.Action)
                         {
                         case System.Collections.Specialized.NotifyCollectionChangedAction.Add when e.NewItems != null:
                             int index = e.NewStartingIndex;
                             foreach ({{viewModelPropertyType}} vm in e.NewItems)
                             {
                                 Model.{{modelPropertyName}}.Insert(index++, vm.Model);
                             }
                             break;
                         case System.Collections.Specialized.NotifyCollectionChangedAction.Remove when e.OldItems != null:
                             foreach ({{viewModelPropertyType}} vm in e.OldItems)
                             {
                                  Model.{{modelPropertyName}}.Remove(vm.Model);
                             }
                             break;
                         case System.Collections.Specialized.NotifyCollectionChangedAction.Move:
                             var modelToMove =  Model.{{modelPropertyName}}[e.OldStartingIndex];
                             Model.{{modelPropertyName}}.RemoveAt(e.OldStartingIndex);
                             Model.{{modelPropertyName}}.Insert(e.NewStartingIndex, modelToMove);
                             break;
                         case System.Collections.Specialized.NotifyCollectionChangedAction.Replace when e.NewItems != null:
                             int replaceIndex = e.NewStartingIndex;
                             foreach ({{viewModelPropertyType}} vm in e.NewItems)
                             {
                                 Model.{{modelPropertyName}}[replaceIndex++] = vm.Model;
                             }
                             break;
                         case System.Collections.Specialized.NotifyCollectionChangedAction.Reset:
                             Model.{{modelPropertyName}}.Clear();
                             foreach ({{viewModelPropertyType}} vm in {{viewModelPropertyName}})
                             {
                                 Model.{{modelPropertyName}}.Add(vm.Model);
                             }
                             break;
                         }   
                     }
                 """,
            DataType.Converter =>
                $$"""
                    partial void On{{viewModelPropertyName}}Changed({{viewModelPropertyType}} value)
                    {
                        Model.{{modelPropertyName}} = Set{{converterName}}(value);
                    }

                    private static partial {{viewModelPropertyType}} Get{{converterName}}({{modelPropertyType}} value);
                    private static partial {{modelPropertyType}} Set{{converterName}}({{viewModelPropertyType}} value);
                """,
            _ => throw new ArgumentOutOfRangeException(nameof(dataType), dataType, null)
        };
    }
}
