using GeneratorLibrary;
using Microsoft.CodeAnalysis;
using System;
using System.Linq;
using System.Reflection;
using System.Text;

namespace MvvmToolbox.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public partial class ObservableModelGenerator : Generator
{
    private const string ObservableModelObjectAttribute = "MvvmToolbox.ComponentModel.ObservableModelObjectAttribute";
    private const string ObservableModelPropertyAttribute = "MvvmToolbox.ComponentModel.ObservableModelPropertyAttribute";

    //private const string FindFieldsGeneratorAttribute = "MediaDevices.FindFieldsGeneratorAttribute";
    //private const string EnumGuidAttribute = "MediaDevices.EnumGuidAttribute";
    //private const string KeyAttribute = "MediaDevices.KeyAttribute";

    public override void Execute()
    {
        //Location errorLocation = propertySyntax.GetLocation();
        //string propertyName = propertySyntax.Identifier.Text;

        //Diagnostic diagnostic = Diagnostic.Create(GeneratorDiagnostics.InvalidPropertyError, errorLocation, propertyName);  // Befüllt das '{0}' im messageFormat
        //Context.ReportDiagnostic(diagnostic);

        //ReportError("Test");

        //Debugger.Launch();
        CreateDebug();

        // get all classes with [ObservableModelObjectAttribute] 
        foreach (var cl in GetAllClassesWithAttribute(ObservableModelObjectAttribute))
        {
            CreateClassFile(cl);
        }
       
    }

    protected override void CreateAttributes(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource($"ObservableModelAttributes.g.cs",
            """
            namespace MvvmToolbox.ComponentModel;

            [AttributeUsage(AttributeTargets.Class)]
            public class ObservableModelObjectAttribute(Type modelType): Attribute
            { 
                public Type ModelType { get; } = modelType;
            }

            [AttributeUsage(AttributeTargets.Property)]
            public class ObservableModelPropertyAttribute : Attribute
            { 
                public ObservableModelPropertyAttribute()
                {
                    ModelPropertyName = string.Empty;
                }

                public ObservableModelPropertyAttribute(string modelPropertyName)
                {
                    ModelPropertyName = modelPropertyName;
                }

                public string ModelPropertyName { get; } 
            }

            """);
    }

    private void CreateClassFile(Class cl)
    {
        var attr = cl.GetAttribute(ObservableModelObjectAttribute);
        string test = attr != null ? attr.ConstructorArguments.FirstOrDefault().Value : string.Empty;
        

        StringBuilder sb = new(
            $$"""
            // <auto-generated />

            #nullable enable annotations
            #nullable disable warnings

            // Suppress warnings about [Obsolete] member usage in generated code.
            #pragma warning disable CS0612, CS0618
            
            namespace {{cl.NameSpace}};

            partial class {{cl.Name}}
            {
                public readonly {{test}} Model;
                
                public {{cl.Name}}({{test}} model)
                {
                    Model = model;

            """);

        foreach (var prop in cl.Properties)
        {
            var propAttr = prop.GetAttribute(ObservableModelPropertyAttribute);
            if (propAttr != null)
            {
                string modelPropName = propAttr.ConstructorArguments.FirstOrDefault()?.Value ?? prop.Name;
                if (prop.Type.IsObservableCollection)
                {
                    //string x = prop.Type.FullNameWithoutConcreteTypes;
                    var innerType = prop.Type.GetInnerType()!;
                    if (innerType.ImplementsInterface("System.ComponentModel.INotifyPropertyChanged"))
                    {
                        string viewModelTypeName = innerType.FullName;
                        sb.AppendLine(
                            $$"""
                                {{prop.Name}} = [.. model.{{modelPropName}}.Select(m => new {{viewModelTypeName}}(m))]; 
                                {{prop.Name}}.CollectionChanged += On{{prop.Name}}CollectionChanged; 
                        """);
                    }
                    else
                    {

                        sb.AppendLine(
                            $$"""
                                {{prop.Name}} = [.. model.{{modelPropName}}]; 
                                {{prop.Name}}.CollectionChanged += On{{prop.Name}}CollectionChanged; 
                        """);
                    }
                }
                else
                {
                    sb.AppendLine(
                        $$"""
                                {{prop.Name}} = model.{{modelPropName}}; 
                        """);
                }
                
            }
        }

        sb.AppendLine(
            """
                }

            """);

        foreach (var prop in cl.Properties)
        {
            var propAttr = prop.GetAttribute(ObservableModelPropertyAttribute);
            if (propAttr != null)
            {
                string modelPropName = propAttr.ConstructorArguments.FirstOrDefault()?.Value ?? prop.Name;

                if (prop.Type.IsObservableCollection)
                {
                    var innerType = prop.Type.GetInnerType()!;
                    if (innerType.ImplementsInterface("System.ComponentModel.INotifyPropertyChanged"))
                    {
                        string viewModelTypeName = innerType.FullName;
                        sb.AppendLine(
                            $$"""
                                private void On{{prop.Name}}CollectionChanged(object? sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                                {
                                    switch (e.Action)
                                    {
                                    case System.Collections.Specialized.NotifyCollectionChangedAction.Add when e.NewItems != null:
                                        int index = e.NewStartingIndex;
                                        foreach ({{viewModelTypeName}} vm in e.NewItems)
                                        {
                                            Model.{{modelPropName}}.Insert(index++, vm.Model);
                                        }
                                        break;

                                    case System.Collections.Specialized.NotifyCollectionChangedAction.Remove when e.OldItems != null:
                                        foreach ({{viewModelTypeName}} vm in e.OldItems)
                                        {
                                             Model.{{modelPropName}}.Remove(vm.Model);
                                        }
                                        break;

                                    case System.Collections.Specialized.NotifyCollectionChangedAction.Move:
                                        var modelToMove =  Model.{{modelPropName}}[e.OldStartingIndex];
                                        Model.{{modelPropName}}.RemoveAt(e.OldStartingIndex);
                                        Model.{{modelPropName}}.Insert(e.NewStartingIndex, modelToMove);
                                        break;

                                    case System.Collections.Specialized.NotifyCollectionChangedAction.Replace when e.NewItems != null:
                                        int replaceIndex = e.NewStartingIndex;
                                        foreach ({{viewModelTypeName}} vm in e.NewItems)
                                        {
                                            Model.{{modelPropName}}[replaceIndex++] = vm.Model;
                                        }
                                        break;
                                    case System.Collections.Specialized.NotifyCollectionChangedAction.Reset:
                                        Model.{{modelPropName}}.Clear();
                                        foreach ({{viewModelTypeName}} vm in {{prop.Name}})
                                        {
                                            Model.{{modelPropName}}.Add(vm.Model);
                                        }
                                        break;
                                    }   
                                }
                            """);
                    }
                    else
                    {
                        string viewModelTypeName = innerType.FullName;
                        sb.AppendLine(
                            $$"""
                                private void On{{prop.Name}}CollectionChanged(object? sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                                {
                                    switch (e.Action)
                                    {
                                    case System.Collections.Specialized.NotifyCollectionChangedAction.Add when e.NewItems != null:
                                        int index = e.NewStartingIndex;
                                        foreach ({{viewModelTypeName}} item in e.NewItems)
                                        {
                                            Model.{{modelPropName}}.Insert(index++, item);
                                        }
                                        break;

                                    case System.Collections.Specialized.NotifyCollectionChangedAction.Remove when e.OldItems != null:
                                        foreach ({{viewModelTypeName}} item in e.OldItems)
                                        {
                                             Model.{{modelPropName}}.Remove(item);
                                        }
                                        break;

                                    case System.Collections.Specialized.NotifyCollectionChangedAction.Move:
                                        var modelToMove =  Model.{{modelPropName}}[e.OldStartingIndex];
                                        Model.{{modelPropName}}.RemoveAt(e.OldStartingIndex);
                                        Model.{{modelPropName}}.Insert(e.NewStartingIndex, modelToMove);
                                        break;

                                    case System.Collections.Specialized.NotifyCollectionChangedAction.Replace when e.NewItems != null:
                                        int replaceIndex = e.NewStartingIndex;
                                        foreach ({{viewModelTypeName}} item in e.NewItems)
                                        {
                                            Model.{{modelPropName}}[replaceIndex++] = item;
                                        }
                                        break;
                                    case System.Collections.Specialized.NotifyCollectionChangedAction.Reset:
                                        Model.{{modelPropName}}.Clear();
                                        foreach ({{viewModelTypeName}} item in {{prop.Name}})
                                        {
                                            Model.{{modelPropName}}.Add(item);
                                        }
                                        break;
                                    }   
                                }
                            """);

                    }
                }
                else
                {
                    
                    sb.AppendLine(
                        $$"""
                            partial void On{{prop.Name}}Changed({{prop.Type.FullName}} value)
                            {
                                Model.{{modelPropName}} = value;
                            }

                        """);
                }
            }
        }

        sb.AppendLine(
            """
            }
            """);
        AddSource($"{cl.Name}.g.cs", sb.ToString());
    }

    public enum DataType
    {
        Error,
        Simple,
        Model,
        List,
        ModelList,
        Lambda,
    }

    public string CreateConstructorLine(DataType dataType, string viewModelPropertyName, string viewModelPropertyType, string modelPropertyName )
    {
        return dataType switch
        {
            DataType.Error => string.Empty,
            DataType.Simple =>      
                $"    {viewModelPropertyName} = model.{modelPropertyName};",
            DataType.Model =>       
                $"    {viewModelPropertyName} = new {viewModelPropertyType}(model.{modelPropertyName});",
            DataType.List =>        
                $$"""
                    {{viewModelPropertyName}} = [.. model.{{modelPropertyName}}];
                    {{viewModelPropertyName}}.CollectionChanged += On{{modelPropertyName}}
                """,
            DataType.ModelList =>   
                $$"""
                    {{viewModelPropertyName}} = [.. model.{{modelPropertyName}}.Select(m => new {viewModelPropertyType}(m))];
                    {{viewModelPropertyName}}.CollectionChanged += On{{modelPropertyName}}
                """,
            //DataType.Lambda => "Lambda",
            //    $"    {viewModelPropertyName} = get(model.{modelPropertyName});",
            _ => throw new ArgumentOutOfRangeException(nameof(dataType), dataType, null)
        };
    }

    public string CreateSetterMethods(DataType dataType, string viewModelPropertyName, string viewModelPropertyType, string modelPropertyName)
    {
        return dataType switch
        {
            DataType.Error => string.Empty,
            DataType.Simple =>
                $$"""
                    partial void On{{viewModelPropertyName}}Changed({{viewModelPropertyType}} value)
                    {
                        Model.{{modelPropertyName}} = value;
                    }

                """,
        DataType.Model =>
                $$"""
                    partial void On{{viewModelPropertyName}}Changed({{viewModelPropertyType}} value)
                    {
                        Model.{{modelPropertyName}} = value.Model;
                    }

                """,
            DataType.List =>
                $$"""
                    private void On{{prop.Name}}CollectionChanged(object? sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                    {
                        switch (e.Action)
                        {
                        case System.Collections.Specialized.NotifyCollectionChangedAction.Add when e.NewItems != null:
                            int index = e.NewStartingIndex;
                            foreach ({{viewModelTypeName}} item in e.NewItems)
                            {
                                Model.{{modelPropName}}.Insert(index++, item);
                            }
                            break;
                        case System.Collections.Specialized.NotifyCollectionChangedAction.Remove when e.OldItems != null:
                            foreach ({{viewModelTypeName}} item in e.OldItems)
                            {
                                 Model.{{modelPropName}}.Remove(item);
                            }
                            break;
                        case System.Collections.Specialized.NotifyCollectionChangedAction.Move:
                            var modelToMove =  Model.{{modelPropName}}[e.OldStartingIndex];
                            Model.{{modelPropName}}.RemoveAt(e.OldStartingIndex);
                            Model.{{modelPropName}}.Insert(e.NewStartingIndex, modelToMove);
                            break;
                        case System.Collections.Specialized.NotifyCollectionChangedAction.Replace when e.NewItems != null:
                            int replaceIndex = e.NewStartingIndex;
                            foreach ({{viewModelTypeName}} item in e.NewItems)
                            {
                                Model.{{modelPropName}}[replaceIndex++] = item;
                            }
                            break;
                        case System.Collections.Specialized.NotifyCollectionChangedAction.Reset:
                            Model.{{modelPropName}}.Clear();
                            foreach ({{viewModelTypeName}} item in {{prop.Name}})
                            {
                                Model.{{modelPropName}}.Add(item);
                            }
                            break;
                        }   
                    }
                """);
        DataType.ModelList =>
                $$"""
                    {{viewModelPropertyName}} = [.. model.{{modelPropertyName}}.Select(m => new {viewModelPropertyType}(m))];
                    {{viewModelPropertyName}}.CollectionChanged += On{{modelPropertyName}}
                """,
            //DataType.Lambda => "Lambda",
            //    $"    {viewModelPropertyName} = get(model.{modelPropertyName});",
            _ => throw new ArgumentOutOfRangeException(nameof(dataType), dataType, null)
        };
    }
}
